### ISSUE TITLE
Permission denied for git clone from GCP

### ISSUE THREAD

**Issue by ulfimlg** [mdai/ml-lessons#4]
Clone ml-lessons repo from github on instance
After changing directory to /opt/deeplearning/workspace and running 
`git clone https://github.com/mdai/ml-lessons.git`
 I get this error:

> fatal: could not create work tree dir 'ml-lessons': Permission denied

Any idea why this is happening?

**Comment by tmoneyx01** [comment]
i dont think you have write permission in your current directory. where are you trying to do this? 
see https://stackoverflow.com/questions/16376035/fatal-could-not-create-work-tree-dir-kivy

**Comment by ulfimlg** [comment]
```
sudo chmod 777 DIR_NAME
cd DIR_NAME
git clone https://github.com/mdai/ml-lessons.git
```
Yes, it worked after the permissions were changed.
