### ISSUE TITLE
lesson1-xray-images-classification.ipynb : Exception Call project.prepare() first.

### ISSUE THREAD

**Issue by hazkaz** [mdai/ml-lessons#9]
I understand that the notebook is a bit old. Anyway I tried it with the latest release of mdai-python-client and inspite of calling project.prepare() , it raised the error.

I didn't dive too deep into the code, but I called some private methods and found an exception which was not raised when prepare was called:-
`ValueError: Unable to create UID from L_lVzGql`

---

![image](https://user-images.githubusercontent.com/11059720/65820274-79c33300-e244-11e9-87f2-01d5aa6a5d4e.png)

**Comment by tobimichigan** [comment]
Just submitted an issue on this too, before reading yours. I wonder if  any of the admin is reading these.

**Comment by hazkaz** [comment]
I don't think so...

**Comment by transcranial** [comment]
The notebook has been updated, and everything should be working.

**Comment by wizardofrobots** [comment]
Works now...thanks
